### ISSUE TITLE
只是想告诉你，我在关注dotbpe！

### ISSUE THREAD

**Issue by hassiumsoft** [xuanye/dotbpe#1]
坚持下去。我下个项目打算用。

**Comment by xuanye** [comment]
先别用啊，我还在调整API中。。

**Comment by hassiumsoft** [comment]
@xuanye 
你好，看了你的代码，host这部分是参照aspnethostcore重写的。。
我最近在写一个game框架。host直接 引用的是Microsoft.Extensions.Hosting（非web，地址在下面）这部分。然后继承了其IHostedService接口来启动dotnetty的bootstrap，这样可以减少host部分的重写，而且复用性更高。

如果可以的话，希望你能这样的处理下，让你的rpc部分与host分开，更能独立出来。
项目中只要引用这两个项目，就可以启动一个简单的控制台
https://github.com/aspnet/Hosting/tree/dev/src/Microsoft.Extensions.Hosting.Abstractions
https://github.com/aspnet/Hosting/tree/dev/src/Microsoft.Extensions.Hosting

**Comment by xuanye** [comment]
@hassiumsoft 好的，我稍后具体看看 谢谢你的建议

**Comment by xuanye** [comment]
@hassiumsoft  我看下了代码，这个应该是dotnet core 2.1 版本新分出来的功能，2.0.x 还不能用，我暂时吧 相关的代码copy 过来，到时候正式发布了调整一下才行，确实代码要优雅简介很多

**Comment by hassiumsoft** [comment]
@xuanye 对的.我用的时候是从他的github上直接拉下来的..如果要使用nuget的话,估计得等他正式发布了
